language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: OT64ZIhtAiNSuoTk8V2PAXcLXDHLPKTwKJf67Xi8mO1UD93KrDgET3r0zFSKSEcVA/Y5VLQA0krXjTOIyuudwNrdbvuZUVZCIRl96UG1on/pVPcP7muF83rSjAjajJQgxPxnGcGhucVc1h8VfCJupI1J9jIt6r5gLl0C+Q4W0cnuqLvl8s/aGxMsEgsBtRjHJj7cMCV7wBbSIY3xfYAZ9uLx4wdQAkCdtii8klWxBlQNXVvhFmqbu6XmZPC93yosP3vun7bH+X7mACyybwzNDssFj7fAaLHy/7UATI31k6gPzCk1UwEwJzM17LJJRtAKEF8aTM4pWyqx6a+g+re/pFlarsjPUFGEZxfboB+MizoHip0IAwiYijNb09u7/8gDJKuy9Dj9zya5cjkcJDLqnrQmBaO0UhruY583X93UcYOrmUV7EwOaKj9mhKAuD0nk7Kr4Rcx+Q8UUzforra2/a+cdKLpvoxqaCOx09ssD93T4j2tt93vkg9l/uaMp71liBVgj4JamKoHoKMmQsiSn6MLJ7PMz5I7XKO5DqCkXQFXA2QVomQlRr5gKjQN+VMhMsifNwFhj9SMRaCp2Fo2HTCp0A+vjiAao6dJDPFOXr/cgi7rYhHx1hmS2umzoWETj68ZuUHVUFzgkdn/KPQuNuzoO9jEKBFqcaNG3WXM+sUo=
