language: node_js
node_js:
- 5.6
before_script:
- gem install percy-cli
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: OT64ZIhtAiNSuoTk8V2PAXcLXDHLPKTwKJf67Xi8mO1UD93KrDgET3r0zFSKSEcVA/Y5VLQA0krXjTOIyuudwNrdbvuZUVZCIRl96UG1on/pVPcP7muF83rSjAjajJQgxPxnGcGhucVc1h8VfCJupI1J9jIt6r5gLl0C+Q4W0cnuqLvl8s/aGxMsEgsBtRjHJj7cMCV7wBbSIY3xfYAZ9uLx4wdQAkCdtii8klWxBlQNXVvhFmqbu6XmZPC93yosP3vun7bH+X7mACyybwzNDssFj7fAaLHy/7UATI31k6gPzCk1UwEwJzM17LJJRtAKEF8aTM4pWyqx6a+g+re/pFlarsjPUFGEZxfboB+MizoHip0IAwiYijNb09u7/8gDJKuy9Dj9zya5cjkcJDLqnrQmBaO0UhruY583X93UcYOrmUV7EwOaKj9mhKAuD0nk7Kr4Rcx+Q8UUzforra2/a+cdKLpvoxqaCOx09ssD93T4j2tt93vkg9l/uaMp71liBVgj4JamKoHoKMmQsiSn6MLJ7PMz5I7XKO5DqCkXQFXA2QVomQlRr5gKjQN+VMhMsifNwFhj9SMRaCp2Fo2HTCp0A+vjiAao6dJDPFOXr/cgi7rYhHx1hmS2umzoWETj68ZuUHVUFzgkdn/KPQuNuzoO9jEKBFqcaNG3WXM+sUo=
env:
  global:
    secure: I0wQARwIQfPZgD59yFEB+AxUITIguo2bTSj16z3pnzamaeXTfWQE2V56w5G/lSry7iB79lny8IeZFsaOG3rq53wXWkn/Q49Hj8JKyqRXx/YP96z8yfgtFHcXxXamILrC2Zqftux9cyMiKHaNL3ossQDgz9o1rZkLlFtCJJaaRW6nQckZboJw9BSJaW+OgeaD0fPrFjZVuLc/LjsjIIOjNEfNzeX1lLvnxCPEFQXNLCyv+KtUOH6HaX4OKPkRhezyQ9J2H45Tf7jqmaDfdNraPgsvM5HSeeuqBHokBiGTb7EBbwF687e67V+NrPGnDScOrzJpok8R/QnsgCZyaRP7wfLh6ScrREAdmLk80GUKXsGf3UTFXSfVmrq7NL8ybPDotLHtvhxcR2omgQrxpgaaabHWJEVBXDu93j1m6qgEi5db1wMGfNpmYZp6/bKj+b5BvnJIVoEDAZBWUh2o5r7Xd83lHzpFymauqYXCOm1WENqps1Xo8YO6NYtvAPZENqXN2DeuuNA+LPAj7TjKJZA7HWWy57WKVtRHDEYt7rgQD/wJ0pMe+pFN+D1F3gowbSjOLBsxqT0SCMXrCO87nSJb2/8vVOteWPifADQvmsVYwNPsg3txB8WtGx4MecF9yCUooXmd92kvYYlE68bjKTlV4wllbZ2xmdORCM80YVYLuuM=
